### Form Data - Create User Account
POST {{baseUrl}}/post
Content-Type: application/x-www-form-urlencoded

username=polly&email=polly@polyactyl.dev&role=admin

###

### Bearer Token Authorization
GET {{baseUrl}}/bearer
Authorization: Bearer {{apiKey}}

###

### Custom Headers
GET {{baseUrl}}/get
X-Custom-Header: Polyactyl
X-Api-Key: {{apiKey}}
Accept: application/json

###

### GraphQL Query
POST {{baseUrl}}/post
Content-Type: application/json

query {
  user(id: 1) {
    name
    email
    posts {
      title
    }
  }
}

###

### XML Content
POST {{baseUrl}}/post
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<request>
  <name>Polly</name>
  <message>Testing XML with Polyactyl</message>
</request>

###

### Large JSON Payload
POST {{baseUrl}}/post
Content-Type: application/json

{
  "items": [
    {"id": 1, "name": "Item 1", "price": 19.99},
    {"id": 2, "name": "Item 2", "price": 29.99},
    {"id": 3, "name": "Item 3", "price": 39.99},
    {"id": 4, "name": "Item 4", "price": 49.99},
    {"id": 5, "name": "Item 5", "price": 59.99}
  ],
  "metadata": {
    "timestamp": "2026-06-16T00:00:00Z",
    "version": "1.0",
    "client": "Polyactyl HTTP Client"
  }
}

###

### Basic Authentication
GET {{baseUrl}}/basic-auth/{{username}}/{{password}}
Authorization: Basic {{username}} {{password}}

###

### HTTP Redirect
GET {{baseUrl}}/redirect/3

###

### Different Content Types
PUT {{baseUrl}}/put
Content-Type: text/plain

This is plain text content being sent to the server.
