### HTTPBin - Simple GET
GET {{baseUrl}}/get

###

### HTTPBin - POST with JSON
POST {{baseUrl}}/post
Content-Type: application/json

{
  "name": "Polly",
  "message": "Hello from Polyactyl!"
}

###

### HTTPBin - Headers
GET {{baseUrl}}/headers

###

### HTTPBin - Status Code (200)
GET {{baseUrl}}/status/200

###

### HTTPBin - Status Code (404)
GET {{baseUrl}}/status/404

###

### HTTPBin - Delay Response (5 seconds)
GET {{baseUrl}}/delay/5

###

### HTTPBin - IP Address
GET {{baseUrl}}/ip

###

### HTTPBin - User Agent
GET {{baseUrl}}/user-agent
