### PokéAPI - Get Pokémon
GET https://pokeapi.co/api/v2/pokemon/pikachu

###

### PokéAPI - Get Multiple Pokémon
GET https://pokeapi.co/api/v2/pokemon?limit=5&offset=0

###

### PokéAPI - Get Type Info
GET https://pokeapi.co/api/v2/type/electric

###

### ReqRes - Get Users
GET {{reqresBaseUrl}}/users

###

### ReqRes - Get Single User
GET {{reqresBaseUrl}}/users/{{userId}}

###

### ReqRes - Create User
POST {{reqresBaseUrl}}/users
Content-Type: application/json

{
  "name": "morpheus",
  "job": "leader"
}

###

### ReqRes - Update User
PUT {{reqresBaseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "morpheus",
  "job": "zion resident"
}

###

### ReqRes - Delete User
DELETE {{reqresBaseUrl}}/users/{{userId}}

###

### Dog CEO API - Random Dog Image
GET https://dog.ceo/api/breeds/image/random

###

### Dog CEO API - List All Breeds
GET https://dog.ceo/api/breeds/list/all
